export interface FontDefinition {
  label: string;
  value: string;
  category: "Sans Serif" | "Serif" | "Display" | "Handwriting" | "Monospace";
}

export const GOOGLE_FONTS: FontDefinition[] = [
  // ============================================================
  // SANS SERIF
  // ============================================================
  { label: "Roboto", value: "'Roboto', sans-serif", category: "Sans Serif" },
  { label: "Open Sans", value: "'Open Sans', sans-serif", category: "Sans Serif" },
  { label: "Lato", value: "'Lato', sans-serif", category: "Sans Serif" },
  { label: "Montserrat", value: "'Montserrat', sans-serif", category: "Sans Serif" },
  { label: "Oswald", value: "'Oswald', sans-serif", category: "Sans Serif" },
  { label: "Source Sans Pro", value: "'Source Sans Pro', sans-serif", category: "Sans Serif" },
  { label: "Raleway", value: "'Raleway', sans-serif", category: "Sans Serif" },
  { label: "PT Sans", value: "'PT Sans', sans-serif", category: "Sans Serif" },
  { label: "Poppins", value: "'Poppins', sans-serif", category: "Sans Serif" },
  { label: "Inter", value: "'Inter', sans-serif", category: "Sans Serif" },
  { label: "Ubuntu", value: "'Ubuntu', sans-serif", category: "Sans Serif" },
  { label: "Nunito", value: "'Nunito', sans-serif", category: "Sans Serif" },
  { label: "Rubik", value: "'Rubik', sans-serif", category: "Sans Serif" },
  { label: "Work Sans", value: "'Work Sans', sans-serif", category: "Sans Serif" },
  { label: "Fira Sans", value: "'Fira Sans', sans-serif", category: "Sans Serif" },
  { label: "Quicksand", value: "'Quicksand', sans-serif", category: "Sans Serif" },
  { label: "Barlow", value: "'Barlow', sans-serif", category: "Sans Serif" },
  { label: "Nunito Sans", value: "'Nunito Sans', sans-serif", category: "Sans Serif" },
  { label: "Titillium Web", value: "'Titillium Web', sans-serif", category: "Sans Serif" },
  { label: "Heebo", value: "'Heebo', sans-serif", category: "Sans Serif" },
  { label: "Dosis", value: "'Dosis', sans-serif", category: "Sans Serif" },
  { label: "Libre Franklin", value: "'Libre Franklin', sans-serif", category: "Sans Serif" },
  { label: "Josefin Sans", value: "'Josefin Sans', sans-serif", category: "Sans Serif" },
  { label: "Karla", value: "'Karla', sans-serif", category: "Sans Serif" },
  { label: "Arimo", value: "'Arimo', sans-serif", category: "Sans Serif" },
  { label: "Oxygen", value: "'Oxygen', sans-serif", category: "Sans Serif" },
  { label: "Mukta", value: "'Mukta', sans-serif", category: "Sans Serif" },
  { label: "Cabin", value: "'Cabin', sans-serif", category: "Sans Serif" },
  { label: "Hind", value: "'Hind', sans-serif", category: "Sans Serif" },
  { label: "Exo 2", value: "'Exo 2', sans-serif", category: "Sans Serif" },
  { label: "Asap", value: "'Asap', sans-serif", category: "Sans Serif" },
  { label: "Expletive Sans", value: "'Expletive Sans', sans-serif", category: "Sans Serif" },
  { label: "DM Sans", value: "'DM Sans', sans-serif", category: "Sans Serif" },
  { label: "IBM Plex Sans", value: "'IBM Plex Sans', sans-serif", category: "Sans Serif" },
  { label: "Mulish", value: "'Mulish', sans-serif", category: "Sans Serif" },
  { label: "Manrope", value: "'Manrope', sans-serif", category: "Sans Serif" },
  { label: "Plus Jakarta Sans", value: "'Plus Jakarta Sans', sans-serif", category: "Sans Serif" },
  { label: "Sora", value: "'Sora', sans-serif", category: "Sans Serif" },
  { label: "Outfit", value: "'Outfit', sans-serif", category: "Sans Serif" },
  { label: "Urbanist", value: "'Urbanist', sans-serif", category: "Sans Serif" },
  { label: "Albert Sans", value: "'Albert Sans', sans-serif", category: "Sans Serif" },
  { label: "Figtree", value: "'Figtree', sans-serif", category: "Sans Serif" },
  { label: "Lexend", value: "'Lexend', sans-serif", category: "Sans Serif" },
  { label: "Onest", value: "'Onest', sans-serif", category: "Sans Serif" },
  { label: "Familjen Grotesk", value: "'Familjen Grotesk', sans-serif", category: "Sans Serif" },
  { label: "Be Vietnam Pro", value: "'Be Vietnam Pro', sans-serif", category: "Sans Serif" },
  { label: "Instrument Sans", value: "'Instrument Sans', sans-serif", category: "Sans Serif" },
  { label: "Space Grotesk", value: "'Space Grotesk', sans-serif", category: "Sans Serif" },
  { label: "Glory", value: "'Glory', sans-serif", category: "Sans Serif" },
  { label: "Epilogue", value: "'Epilogue', sans-serif", category: "Sans Serif" },
  { label: "Bricolage Grotesque", value: "'Bricolage Grotesque', sans-serif", category: "Sans Serif" },
  { label: "Libre Caslon Text", value: "'Libre Caslon Text', serif", category: "Sans Serif" },

  // ============================================================
  // SERIF
  // ============================================================
  { label: "Playfair Display", value: "'Playfair Display', serif", category: "Serif" },
  { label: "Lora", value: "'Lora', serif", category: "Serif" },
  { label: "Merriweather", value: "'Merriweather', serif", category: "Serif" },
  { label: "PT Serif", value: "'PT Serif', serif", category: "Serif" },
  { label: "Crimson Text", value: "'Crimson Text', serif", category: "Serif" },
  { label: "EB Garamond", value: "'EB Garamond', serif", category: "Serif" },
  { label: "Bitter", value: "'Bitter', serif", category: "Serif" },
  { label: "Libre Baskerville", value: "'Libre Baskerville', serif", category: "Serif" },
  { label: "Bree Serif", value: "'Bree Serif', serif", category: "Serif" },
  { label: "Vollkorn", value: "'Vollkorn', serif", category: "Serif" },
  { label: "Cormorant Garamond", value: "'Cormorant Garamond', serif", category: "Serif" },
  { label: "Zilla Slab", value: "'Zilla Slab', serif", category: "Serif" },
  { label: "Tinos", value: "'Tinos', serif", category: "Serif" },
  { label: "Domine", value: "'Domine', serif", category: "Serif" },
  { label: "Spectral", value: "'Spectral', serif", category: "Serif" },
  { label: "Source Serif Pro", value: "'Source Serif Pro', serif", category: "Serif" },
  { label: "Noto Serif", value: "'Noto Serif', serif", category: "Serif" },
  { label: "Cardo", value: "'Cardo', serif", category: "Serif" },
  { label: "Garamond", value: "'Garamond', serif", category: "Serif" },
  { label: "Libre Caslon Display", value: "'Libre Caslon Display', serif", category: "Serif" },
  { label: "Rosarivo", value: "'Rosarivo', serif", category: "Serif" },
  { label: "Lustria", value: "'Lustria', serif", category: "Serif" },
  { label: "Alice", value: "'Alice', serif", category: "Serif" },
  { label: "Caudex", value: "'Caudex', serif", category: "Serif" },
  { label: "Gentium Book Plus", value: "'Gentium Book Plus', serif", category: "Serif" },
  { label: "IM Fell English", value: "'IM Fell English', serif", category: "Serif" },
  { label: "Junge", value: "'Junge', serif", category: "Serif" },
  { label: "Lara", value: "'Lara', serif", category: "Serif" },
  { label: "Marcellus", value: "'Marcellus', serif", category: "Serif" },
  { label: "Martel", value: "'Martel', serif", category: "Serif" },
  { label: "Neuton", value: "'Neuton', serif", category: "Serif" },
  { label: "Old Standard TT", value: "'Old Standard TT', serif", category: "Serif" },
  { label: "Playfair Display SC", value: "'Playfair Display SC', serif", category: "Serif" },
  { label: "Sanchez", value: "'Sanchez', serif", category: "Serif" },
  { label: "Slabo 27px", value: "'Slabo 27px', serif", category: "Serif" },
  { label: "Tisa", value: "'Tisa', serif", category: "Serif" },
  { label: "Abril Fatface", value: "'Abril Fatface', display", category: "Serif" },

  // ============================================================
  // DISPLAY / HEADLINE
  // ============================================================
  { label: "Anton", value: "'Anton', sans-serif", category: "Display" },
  { label: "Lobster", value: "'Lobster', cursive", category: "Display" },
  { label: "Bebas Neue", value: "'Bebas Neue', display", category: "Display" },
  { label: "Fjalla One", value: "'Fjalla One', sans-serif", category: "Display" },
  { label: "Comfortaa", value: "'Comfortaa', display", category: "Display" },
  { label: "Fredoka One", value: "'Fredoka One', display", category: "Display" },
  { label: "Carter One", value: "'Carter One', display", category: "Display" },
  { label: "Concert One", value: "'Concert One', display", category: "Display" },
  { label: "Francois One", value: "'Francois One', sans-serif", category: "Display" },
  { label: "Yeseva One", value: "'Yeseva One', display", category: "Display" },
  { label: "Chewy", value: "'Chewy', display", category: "Display" },
  { label: "Lilita One", value: "'Lilita One', display", category: "Display" },
  { label: "Bangers", value: "'Bangers', display", category: "Display" },
  { label: "Boogaloo", value: "'Boogaloo', display", category: "Display" },
  { label: "Oleo Script", value: "'Oleo Script', display", category: "Display" },
  { label: "Luckiest Guy", value: "'Luckiest Guy', display", category: "Display" },
  { label: "Baloo 2", value: "'Baloo 2', display", category: "Display" },
  { label: "Candal", value: "'Candal', sans-serif", category: "Display" },
  { label: "Righteous", value: "'Righteous', display", category: "Display" },
  { label: "Alfa Slab One", value: "'Alfa Slab One', display", category: "Display" },
  { label: "Monoton", value: "'Monoton', display", category: "Display" },
  { label: "Audiowide", value: "'Audiowide', display", category: "Display" },
  { label: "Shrikhand", value: "'Shrikhand', display", category: "Display" },
  { label: "Bungee", value: "'Bungee', display", category: "Display" },
  { label: "Passion One", value: "'Passion One', display", category: "Display" },
  { label: "Black Ops One", value: "'Black Ops One', display", category: "Display" },
  { label: "Russo One", value: "'Russo One', display", category: "Display" },
  { label: "Rubik Mono One", value: "'Rubik Mono One', display", category: "Display" },
  { label: "Ruslan Display", value: "'Ruslan Display', display", category: "Display" },
  { label: "Teko", value: "'Teko', display", category: "Display" },
  { label: "Rajdhani", value: "'Rajdhani', display", category: "Display" },
  { label: "Orbitron", value: "'Orbitron', display", category: "Display" },
  { label: "Michroma", value: "'Michroma', display", category: "Display" },
  { label: "Rationale", value: "'Rationale', display", category: "Display" },
  { label: "Staatliches", value: "'Staatliches', display", category: "Display" },
  { label: "Big Shoulders Display", value: "'Big Shoulders Display', display", category: "Display" },
  { label: "Syne", value: "'Syne', display", category: "Display" },
  { label: "Unbounded", value: "'Unbounded', display", category: "Display" },
  { label: "Bebas", value: "'Bebas', display", category: "Display" },
  { label: "Fjalla", value: "'Fjalla', display", category: "Display" },
  { label: "Acme", value: "'Acme', display", category: "Display" },
  { label: "Krona One", value: "'Krona One', display", category: "Display" },
  { label: "Henny Penny", value: "'Henny Penny', display", category: "Display" },
  { label: "Knewave", value: "'Knewave', display", category: "Display" },
  { label: "Titan One", value: "'Titan One', display", category: "Display" },
  { label: "Prosto One", value: "'Prosto One', display", category: "Display" },
  { label: "Wallpoet", value: "'Wallpoet', display", category: "Display" },
  { label: "Codystar", value: "'Codystar', display", category: "Display" },
  { label: "Monofett", value: "'Monofett', display", category: "Display" },
  { label: "Graduate", value: "'Graduate', display", category: "Display" },
  { label: "Dela Gothic One", value: "'Dela Gothic One', display", category: "Display" },
  { label: "Bizon", value: "'Bizon', display", category: "Display" },

  // ============================================================
  // HANDWRITING / SCRIPT
  // ============================================================
  { label: "Pacifico", value: "'Pacifico', cursive", category: "Handwriting" },
  { label: "Dancing Script", value: "'Dancing Script', cursive", category: "Handwriting" },
  { label: "Caveat", value: "'Caveat', cursive", category: "Handwriting" },
  { label: "Satisfy", value: "'Satisfy', cursive", category: "Handwriting" },
  { label: "Amatic SC", value: "'Amatic SC', cursive", category: "Handwriting" },
  { label: "Shadows Into Light", value: "'Shadows Into Light', cursive", category: "Handwriting" },
  { label: "Indie Flower", value: "'Indie Flower', cursive", category: "Handwriting" },
  { label: "Great Vibes", value: "'Great Vibes', cursive", category: "Handwriting" },
  { label: "Sacramento", value: "'Sacramento', cursive", category: "Handwriting" },
  { label: "Kalam", value: "'Kalam', cursive", category: "Handwriting" },
  { label: "Gloria Hallelujah", value: "'Gloria Hallelujah', cursive", category: "Handwriting" },
  { label: "Parisienne", value: "'Parisienne', cursive", category: "Handwriting" },
  { label: "Handlee", value: "'Handlee', cursive", category: "Handwriting" },
  { label: "Berkshire Swash", value: "'Berkshire Swash', cursive", category: "Handwriting" },
  { label: "Lobster Two", value: "'Lobster Two', cursive", category: "Handwriting" },
  { label: "Kaushan Script", value: "'Kaushan Script', cursive", category: "Handwriting" },
  { label: "Yellowtail", value: "'Yellowtail', cursive", category: "Handwriting" },
  { label: "Homemade Apple", value: "'Homemade Apple', cursive", category: "Handwriting" },
  { label: "Ruthie", value: "'Ruthie', cursive", category: "Handwriting" },
  { label: "Aguafina Script", value: "'Aguafina Script', cursive", category: "Handwriting" },
  { label: "Allura", value: "'Allura', cursive", category: "Handwriting" },
  { label: "Arizonia", value: "'Arizonia', cursive", category: "Handwriting" },
  { label: "Artistic", value: "'Artistic', cursive", category: "Handwriting" },
  { label: "Battalo", value: "'Battalo', cursive", category: "Handwriting" },
  { label: "Bonbon", value: "'Bonbon', cursive", category: "Handwriting" },
  { label: "Cedarville Cursive", value: "'Cedarville Cursive', cursive", category: "Handwriting" },
  { label: "Chantelly", value: "'Chantelly', cursive", category: "Handwriting" },
  { label: "Cookie", value: "'Cookie', cursive", category: "Handwriting" },
  { label: "Corinthia", value: "'Corinthia', cursive", category: "Handwriting" },
  { label: "Covered By Your Grace", value: "'Covered By Your Grace', cursive", category: "Handwriting" },
  { label: "Creepster", value: "'Creepster', display", category: "Handwriting" },
  { label: "Devonshire", value: "'Devonshire', cursive", category: "Handwriting" },
  { label: "Emily Candy", value: "'Emily Candy', cursive", category: "Handwriting" },
  { label: "Fasthelp", value: "'Fasthelp', cursive", category: "Handwriting" },
  { label: "Felipa", value: "'Felipa', cursive", category: "Handwriting" },
  { label: "Fondamento", value: "'Fondamento', cursive", category: "Handwriting" },
  { label: "Freehand", value: "'Freehand', cursive", category: "Handwriting" },
  { label: "G Ahead", value: "'G Ahead', cursive", category: "Handwriting" },
  { label: "Germania One", value: "'Germania One', display", category: "Handwriting" },
  { label: "Going Young", value: "'Going Young', cursive", category: "Handwriting" },
  { label: "Grand Hotel", value: "'Grand Hotel', cursive", category: "Handwriting" },
  { label: "Great Outline", value: "'Great Outline', cursive", category: "Handwriting" },
  { label: "Haca", value: "'Haca', cursive", category: "Handwriting" },
  { label: "Happy Monkey", value: "'Happy Monkey', cursive", category: "Handwriting" },
  { label: "Iceberg", value: "'Iceberg', cursive", category: "Handwriting" },
  { label: "Jacques Francois", value: "'Jacques Francois', serif", category: "Handwriting" },
  { label: "Josefin Slab", value: "'Josefin Slab', serif", category: "Handwriting" },
  { label: "Judges", value: "'Judges', cursive", category: "Handwriting" },
  { label: "Julius Sans One", value: "'Julius Sans One', sans-serif", category: "Handwriting" },
  { label: "Junction", value: "'Junction', sans-serif", category: "Handwriting" },
  { label: "Kelly Slab", value: "'Kelly Slab', cursive", category: "Handwriting" },
  { label: "Kingthings", value: "'Kingthings', cursive", category: "Handwriting" },
  { label: "Kylie", value: "'Kylie', cursive", category: "Handwriting" },
  { label: "League Script", value: "'League Script', cursive", category: "Handwriting" },
  { label: "Lemon Tuesday", value: "'Lemon Tuesday', cursive", category: "Handwriting" },
  { label: "Lily Script One", value: "'Lily Script One', cursive", category: "Handwriting" },
  { label: "Loved by the King", value: "'Loved by the King', cursive", category: "Handwriting" },
  { label: "Marck Script", value: "'Marck Script', cursive", category: "Handwriting" },
  { label: "Mervale", value: "'Mervale', serif", category: "Handwriting" },
  { label: "Mf Glfr", value: "'Mf Glfr', cursive", category: "Handwriting" },
  { label: "Milonga", value: "'Milonga', cursive", category: "Handwriting" },
  { label: "Miss Fajardose", value: "'Miss Fajardose', cursive", category: "Handwriting" },
  { label: "Mistro", value: "'Mistro', cursive", category: "Handwriting" },
  { label: "Monte Carlo", value: "'Monte Carlo', cursive", category: "Handwriting" },
  { label: "Moulders", value: "'Moulders', cursive", category: "Handwriting" },
  { label: "Nat", value: "'Nat', cursive", category: "Handwriting" },
  { label: "Niconne", value: "'Niconne', cursive", category: "Handwriting" },
  { label: "Nosifer", value: "'Nosifer', display", category: "Handwriting" },
  { label: "Over the Rainbow", value: "'Over the Rainbow', cursive", category: "Handwriting" },
  { label: "Owt", value: "'Owt', cursive", category: "Handwriting" },
  { label: "Parker", value: "'Parker', cursive", category: "Handwriting" },
  { label: "Patua One", value: "'Patua One', display", category: "Handwriting" },
  { label: "Peggy", value: "'Peggy', cursive", category: "Handwriting" },
  { label: "Permian Sans", value: "'Permian Sans', sans-serif", category: "Handwriting" },
  { label: "Plain Cotton", value: "'Plain Cotton', cursive", category: "Handwriting" },
  { label: "Playball", value: "'Playball', display", category: "Handwriting" },
  { label: "Pompiere", value: "'Pompiere', display", category: "Handwriting" },
  { label: "Preah", value: "'Preah', cursive", category: "Handwriting" },
  { label: "Qwigley", value: "'Qwigley', cursive", category: "Handwriting" },
  { label: "Riesling", value: "'Riesling', cursive", category: "Handwriting" },
  { label: "Rochester", value: "'Rochester', cursive", category: "Handwriting" },
  { label: "Roman", value: "'Roman', cursive", category: "Handwriting" },
  { label: "Rouge Script", value: "'Rouge Script', cursive", category: "Handwriting" },
  { label: "Rubber", value: "'Rubber', cursive", category: "Handwriting" },
  { label: "Sacharas", value: "'Sacharas', cursive", category: "Handwriting" },
  { label: "Sail", value: "'Sail', display", category: "Handwriting" },
  { label: "Sanvito", value: "'Sanvito', cursive", category: "Handwriting" },
  { label: "Scriptina", value: "'Scriptina', cursive", category: "Handwriting" },
  { label: "Sedev", value: "'Sedev', cursive", category: "Handwriting" },
  { label: "Sex", value: "'Sex', cursive", category: "Handwriting" },
  { label: "Shadows Into Light Two", value: "'Shadows Into Light Two', cursive", category: "Handwriting" },
  { label: "Smokum", value: "'Smokum', display", category: "Handwriting" },
  { label: "Snickles", value: "'Snickles', cursive", category: "Handwriting" },
  { label: "Some Time Later", value: "'Some Time Later', display", category: "Handwriting" },
  { label: "Special Elite", value: "'Special Elite', cursive", category: "Handwriting" },
  { label: "Spirax", value: "'Spirax', display", category: "Handwriting" },
  { label: "Spring Sling", value: "'Spring Sling', cursive", category: "Handwriting" },
  { label: "Steve", value: "'Steve', cursive", category: "Handwriting" },
  { label: "Sunshiney", value: "'Sunshiney', cursive", category: "Handwriting" },
  { label: "Swanky", value: "'Swanky', cursive", category: "Handwriting" },
  { label: "Tangerine", value: "'Tangerine', cursive", category: "Handwriting" },
  { label: "Taprom", value: "'Taprom', cursive", category: "Handwriting" },
  { label: "Tenny", value: "'Tenny', cursive", category: "Handwriting" },
  { label: "The Nomad", value: "'The Nomad', cursive", category: "Handwriting" },
  { label: "Thumb", value: "'Thumb', cursive", category: "Handwriting" },
  { label: "Touch of Pink", value: "'Touch of Pink', cursive", category: "Handwriting" },
  { label: "Triqueta", value: "'Triqueta', cursive", category: "Handwriting" },
  { label: "Tyliano", value: "'Tyliano', cursive", category: "Handwriting" },
  { label: "Vast Shadow", value: "'Vast Shadow', display", category: "Handwriting" },
  { label: "Vibur", value: "'Vibur', cursive", category: "Handwriting" },
  { label: "Violet", value: "'Violet', cursive", category: "Handwriting" },
  { label: "Vollkorn SC", value: "'Vollkorn SC', serif", category: "Handwriting" },
  { label: "Waiting for the Sunrise", value: "'Waiting for the Sunrise', cursive", category: "Handwriting" },
  { label: "Walter", value: "'Walter', cursive", category: "Handwriting" },
  { label: "Warnes", value: "'Warnes', display", category: "Handwriting" },
  { label: "Yesteryear", value: "'Yesteryear', cursive", category: "Handwriting" },
  { label: "Zeyada", value: "'Zeyada', cursive", category: "Handwriting" },

  // ============================================================
  // MONOSPACE
  // ============================================================
  { label: "Fira Code", value: "'Fira Code', monospace", category: "Monospace" },
  { label: "JetBrains Mono", value: "'JetBrains Mono', monospace", category: "Monospace" },
  { label: "IBM Plex Mono", value: "'IBM Plex Mono', monospace", category: "Monospace" },
  { label: "Inconsolata", value: "'Inconsolata', monospace", category: "Monospace" },
  { label: "Roboto Mono", value: "'Roboto Mono', monospace", category: "Monospace" },
  { label: "Space Mono", value: "'Space Mono', monospace", category: "Monospace" },
  { label: "Source Code Pro", value: "'Source Code Pro', monospace", category: "Monospace" },
  { label: "Ubuntu Mono", value: "'Ubuntu Mono', monospace", category: "Monospace" },
  { label: "Anonymous Pro", value: "'Anonymous Pro', monospace", category: "Monospace" },
  { label: "Cousine", value: "'Cousine', monospace", category: "Monospace" },
  { label: "Courier Prime", value: "'Courier Prime', monospace", category: "Monospace" },
  { label: "Cutive Mono", value: "'Cutive Mono', monospace", category: "Monospace" },
  { label: "Droid Sans Mono", value: "'Droid Sans Mono', monospace", category: "Monospace" },
  { label: "Fira Mono", value: "'Fira Mono', monospace", category: "Monospace" },
  { label: "Hack", value: "'Hack', monospace", category: "Monospace" },
  { label: "Lekton", value: "'Lekton', sans-serif", category: "Monospace" },
  { label: "Nova Mono", value: "'Nova Mono', monospace", category: "Monospace" },
  { label: "Overpass Mono", value: "'Overpass Mono', monospace", category: "Monospace" },
  { label: "Oxygen Mono", value: "'Oxygen Mono', monospace", category: "Monospace" },
  { label: "PT Mono", value: "'PT Mono', monospace", category: "Monospace" },
  { label: "Share Tech Mono", value: "'Share Tech Mono', monospace", category: "Monospace" },
  { label: "Syne Mono", value: "'Syne Mono', monospace", category: "Monospace" },
  { label: "VT323", value: "'VT323', monospace", category: "Monospace" },
  { label: "Zed Mono", value: "'Zed Mono', monospace", category: "Monospace" },
  { label: "Crimson Pro", value: "'Crimson Pro', serif", category: "Monospace" },
  { label: "Squada One", value: "'Squada One', display", category: "Monospace" },

  // ============================================================
  // REAL ESTATE / PROFESSIONAL
  // ============================================================
  { label: "Glober", value: "'Glober', sans-serif", category: "Sans Serif" },
  { label: "Gotham", value: "'Gotham', sans-serif", category: "Sans Serif" },
  { label: "Proxima Nova", value: "'Proxima Nova', sans-serif", category: "Sans Serif" },
  { label: "Avenir", value: "'Avenir', sans-serif", category: "Sans Serif" },
  { label: "Avenir Next", value: "'Avenir Next', sans-serif", category: "Sans Serif" },
  { label: "Futura", value: "'Futura', sans-serif", category: "Sans Serif" },
  { label: "Gill Sans", value: "'Gill Sans', sans-serif", category: "Sans Serif" },
  { label: "Helvetica Neue", value: "'Helvetica Neue', Helvetica, Arial, sans-serif", category: "Sans Serif" },
  { label: "Century Gothic", value: "'Century Gothic', sans-serif", category: "Sans Serif" },
  { label: "Frutiger", value: "'Frutiger', sans-serif", category: "Sans Serif" },
  { label: "Optima", value: "'Optima', sans-serif", category: "Sans Serif" },
  { label: "Trebuchet MS", value: "'Trebuchet MS', sans-serif", category: "Sans Serif" },
  { label: "Georgia", value: "'Georgia', serif", category: "Serif" },
  { label: "Didot", value: "'Didot', serif", category: "Serif" },
  { label: "Bodoni Moda", value: "'Bodoni Moda', serif", category: "Serif" },
  { label: "Clarendon", value: "'Clarendon', serif", category: "Serif" },
  { label: "Rockwell", value: "'Rockwell', serif", category: "Serif" },
  { label: "Canela", value: "'Canela', serif", category: "Serif" },
  { label: "Sageek", value: "'Sageek', serif", category: "Serif" },

  // ============================================================
  // BOLD / IMPACT
  // ============================================================
  { label: "Impact", value: "'Impact', sans-serif", category: "Display" },
  { label: "Haettenschweiler", value: "'Haettenschweiler', sans-serif", category: "Display" },
  { label: "Dense", value: "'Dense', sans-serif", category: "Display" },
  { label: "Halo", value: "'Halo', sans-serif", category: "Display" },
];

export function generateGoogleFontsUrl(): string {
  const families = GOOGLE_FONTS.map((font) => font.label.replace(/\s+/g, "+"));
  return `https://fonts.googleapis.com/css2?family=${families.join("&family=")}&display=swap`;
}
