update public.project_profile_versions
set profile_json = jsonb_build_object(
  'tagline', coalesce(profile_json->>'tagline', ''),
  'possessionStatus', coalesce(profile_json->>'possessionStatus', ''),
  'reraNumber', coalesce(profile_json->>'reraNumber', ''),
  'positioning', coalesce(profile_json->>'positioning', ''),
  'audienceSegments', coalesce(profile_json->'audienceSegments', profile_json->'audience', '[]'::jsonb),
  'lifestyleAngle', coalesce(profile_json->>'lifestyleAngle', ''),
  'configurations', coalesce(profile_json->'configurations', '[]'::jsonb),
  'sizeRanges', coalesce(profile_json->'sizeRanges', '[]'::jsonb),
  'towersCount', coalesce(profile_json->>'towersCount', ''),
  'floorsCount', coalesce(profile_json->>'floorsCount', ''),
  'totalUnits', coalesce(profile_json->>'totalUnits', ''),
  'specialUnitTypes', coalesce(profile_json->'specialUnitTypes', '[]'::jsonb),
  'parkingFacts', coalesce(profile_json->>'parkingFacts', ''),
  'pricingBand', coalesce(profile_json->>'pricingBand', ''),
  'startingPrice', coalesce(profile_json->>'startingPrice', ''),
  'priceRangeByConfig', coalesce(profile_json->'priceRangeByConfig', '[]'::jsonb),
  'bookingAmount', coalesce(profile_json->>'bookingAmount', ''),
  'paymentPlanSummary', coalesce(profile_json->>'paymentPlanSummary', ''),
  'currentOffers', coalesce(profile_json->'currentOffers', '[]'::jsonb),
  'financingPartners', coalesce(profile_json->'financingPartners', '[]'::jsonb),
  'offerValidity', coalesce(profile_json->>'offerValidity', ''),
  'amenities', coalesce(profile_json->'amenities', '[]'::jsonb),
  'heroAmenities', coalesce(profile_json->'heroAmenities', '[]'::jsonb),
  'nearbyLandmarks', coalesce(profile_json->'nearbyLandmarks', '[]'::jsonb),
  'connectivityPoints', coalesce(profile_json->'connectivityPoints', '[]'::jsonb),
  'travelTimes', coalesce(profile_json->'travelTimes', '[]'::jsonb),
  'locationAdvantages', coalesce(profile_json->'locationAdvantages', '[]'::jsonb),
  'constructionStatus', coalesce(profile_json->>'constructionStatus', ''),
  'milestoneHistory', coalesce(profile_json->'milestoneHistory', '[]'::jsonb),
  'latestUpdate', coalesce(profile_json->>'latestUpdate', ''),
  'completionWindow', coalesce(profile_json->>'completionWindow', ''),
  'approvedClaims', coalesce(profile_json->'approvedClaims', '[]'::jsonb),
  'bannedClaims', coalesce(profile_json->'bannedClaims', '[]'::jsonb),
  'legalNotes', coalesce(profile_json->'legalNotes', '[]'::jsonb),
  'approvalsSummary', coalesce(profile_json->>'approvalsSummary', ''),
  'credibilityFacts', coalesce(profile_json->'credibilityFacts', '[]'::jsonb),
  'investorAngle', coalesce(profile_json->>'investorAngle', ''),
  'endUserAngle', coalesce(profile_json->>'endUserAngle', ''),
  'keyObjections', coalesce(profile_json->'keyObjections', '[]'::jsonb),
  'faqs', coalesce(profile_json->'faqs', '[]'::jsonb),
  'actualProjectImageIds', coalesce(profile_json->'actualProjectImageIds', profile_json->'referenceAssetIds', '[]'::jsonb),
  'sampleFlatImageIds', coalesce(profile_json->'sampleFlatImageIds', '[]'::jsonb)
)
where profile_json is not null;
