with template_seed (
  template_key,
  name,
  description,
  content_job_id,
  allowed_formats,
  lever_signature,
  template_json
) as (
  values
  ('project_launch.editorial_catalog.tower_hero.magazine_spread.v1', 'Editorial Tower Magazine Launch', 'A luxury editorial launch style with the tower as the hero and restrained magazine-like typography.', 'project_launch', ARRAY['4:5', '1:1']::text[], '{"style_family":"editorial_catalog","hero_presentation":"tower_hero_launch","layout_geometry":"magazine_spread","graphic_layer":["thin_frame"],"type_voice":"premium_serif","text_architecture":"project_name_first","mood_mode":"pale_editorial_daylight","density":"lean","brand_visibility":"elegant_signature","visual_mode":"editorialized_truth"}'::jsonb, '{"content_jobs":["project_launch"],"best_for":["premium project launch","architecture-led announcement","editorial reveal"],"avoid_when":["pricing or offer must dominate","information-heavy post"]}'::jsonb),
  ('project_launch.graphic_led.cutout_hero.blob_composition.v1', 'Premium Cutout Blob Launch', 'A premium social-first launch template using a truthful building cutout with elegant blob shapes, soft gradients, and clean brand-led typography.', 'project_launch', ARRAY['4:5', '1:1']::text[], '{"style_family":"graphic_led","hero_presentation":"cutout_hero","layout_geometry":"blob_cutout","graphic_layer":["blob_shapes","soft_gradient_field","thin_frame"],"type_voice":"modern_sans","text_architecture":"project_name_first","mood_mode":"ivory_studio_neutral","density":"medium","brand_visibility":"visible_brand_led","visual_mode":"editorialized_truth"}'::jsonb, '{"best_for":["premium but social-first project launch posts","creative launch announcements","brand awareness posts that should feel less formal than a catalog layout","building cutout compositions with generous negative space"],"avoid_when":["strict luxury catalog layout is required","legal/pricing-heavy ad","no usable building exterior asset is available","the project asset cannot be cut out or cropped"],"visual_notes":["Use the official building asset as a clean architectural cutout.","Do not alter the tower shape, facade rhythm, balcony language, or project scale.","Place the cutout over refined blob shapes or soft abstract forms.","Keep the design premium, not childish or playful.","Use brand colors subtly: warm ivory background, deep charcoal typography, muted gold accents."]}'::jsonb),
  ('project_launch.quiet_luxury.facade_crop.centered_symmetry.v1', 'Quiet Luxury Facade Reveal', 'A calm, premium launch composition with a truthful facade crop and centered balance.', 'project_launch', ARRAY['4:5', '1:1']::text[], '{"style_family":"quiet_luxury","hero_presentation":"facade_crop","layout_geometry":"centered_symmetry","graphic_layer":["soft_gradient_field","thin_frame"],"type_voice":"premium_serif","text_architecture":"one_statement","mood_mode":"warm_sunset_editorial","density":"lean","brand_visibility":"whisper","visual_mode":"editorialized_truth"}'::jsonb, '{"content_jobs":["project_launch"],"best_for":["quiet premium launch","minimal announcement","aspirational project identity"],"avoid_when":["requires many data points","offer-led ad"]}'::jsonb),
  ('project_launch.swiss_grid.facade_crop.left_copy_right_hero.v1', 'Swiss Grid Launch Split', 'A structured left-copy/right-architecture launch template with disciplined grid hierarchy.', 'project_launch', ARRAY['4:5']::text[], '{"style_family":"swiss_grid_premium","hero_presentation":"facade_crop","layout_geometry":"left_copy_right_hero","graphic_layer":["divider_lines","geometric_blocks"],"type_voice":"swiss_clean","text_architecture":"project_name_first","mood_mode":"ivory_studio_neutral","density":"medium","brand_visibility":"visible_brand_led","visual_mode":"editorialized_truth"}'::jsonb, '{"content_jobs":["project_launch"],"best_for":["structured project launch","clean location + project identity","builder-readable premium"],"avoid_when":["ultra-minimal brand recall"]}'::jsonb),
  ('project_launch.minimal.symbolic_centerpiece.centered_symmetry.v1', 'Minimal Symbolic Launch', 'A minimal concept-led launch template using a symbolic premium centerpiece instead of dense project facts.', 'project_launch', ARRAY['4:5', '1:1']::text[], '{"style_family":"minimal","hero_presentation":"symbolic_centerpiece","layout_geometry":"centered_symmetry","graphic_layer":["thin_frame","soft_gradient_field"],"type_voice":"quiet_premium","text_architecture":"one_statement","mood_mode":"ivory_studio_neutral","density":"lean","brand_visibility":"elegant_signature","visual_mode":"concept_led"}'::jsonb, '{"content_jobs":["project_launch"],"best_for":["brand recall","visual-only launch","teaser"],"avoid_when":["truthful architecture must dominate"]}'::jsonb),
  ('project_launch.retro.cutout_hero.blob_cutout.v1', 'Retro Cutout Launch', 'A more expressive cutout launch look using architectural crop and warm retro editorial treatment.', 'project_launch', ARRAY['4:5']::text[], '{"style_family":"retro","hero_presentation":"cutout_hero","layout_geometry":"blob_cutout","graphic_layer":["blob_shapes","paper_depth","thin_frame"],"type_voice":"modern_sans","text_architecture":"slogan_first","mood_mode":"warm_sunset_editorial","density":"medium","brand_visibility":"elegant_signature","visual_mode":"editorialized_truth"}'::jsonb, '{"content_jobs":["project_launch"],"best_for":["creative launch variation","campaign freshness"],"avoid_when":["strict corporate/swiss look required"],"reality_policy":"Use the tower as a cutout or crop. Do not add a new background; use paper depth, warm fields, and abstract forms instead."}'::jsonb),
  ('project_launch.art_poster.cutout_hero.sun_disc.v1', 'Art Poster Sun Disc Cutout', 'A Canva-style premium art poster using the truthful tower cutout over a bold sun-disc composition and refined editorial typography.', 'project_launch', ARRAY['4:5', '1:1']::text[], '{"style_family":"art_poster_premium","hero_presentation":"cutout_hero","layout_geometry":"oversized_sun_disc","graphic_layer":["sun_disc","paper_grain","thin_frame","shadow_lift"],"type_voice":"editorial_sans_serif","text_architecture":"poster_headline_first","mood_mode":"warm_sunset_editorial","density":"medium","brand_visibility":"elegant_signature","visual_mode":"cutout_truth"}'::jsonb, '{"content_jobs":["project_launch"],"best_for":["high-impact launch poster","Instagram creative","artistic but truthful architecture cutout"],"avoid_when":["strict corporate design","no usable exterior cutout asset"],"reality_policy":"Cut out the selected building and place it over abstract shapes only; do not add ocean, skyline, roads, or new buildings."}'::jsonb),
  ('project_launch.art_poster.cutout_hero.abstract_shape_field.v1', 'Abstract Shape Tower Cutout Poster', 'A flexible Canva-style premium poster using a faithful building cutout over a large abstract graphic shape or image-window field. The shape adapts to the brief without becoming factual scenery.', 'project_launch', ARRAY['4:5', '1:1', '9:16']::text[], '{"style_family":"art_poster_premium","hero_presentation":"cutout_hero","layout_geometry":"abstract_shape_field","graphic_layer":["large_abstract_shape","cutout_edge","soft_shadow","editorial_rules","warm_gradient_field"],"type_voice":"bold_editorial_sans","text_architecture":"project_name_plus_slogan","mood_mode":"campaign_adaptive_editorial","density":"medium","brand_visibility":"visible_brand_led","visual_mode":"cutout_truth"}'::jsonb, '{"content_jobs":["project_launch"],"best_for":["premium project launch posters","Canva-style campaign variety","faithful building cutout with artistic background shape","social media launch creatives that need more energy than brochure layouts"],"avoid_when":["strict corporate brochure layout is required","no usable exterior asset exists","the brief requires factual background/location proof"],"shape_selection_rule":"Choose the background shape as a graphic container or mood field, not factual scenery. Shape may be circle, arch, blob, window, contour, diagonal block, rounded plate, or monogram-like form based on the brief. Do not place factual scenery inside the shape unless grounded by the selected asset.","reality_policy":"Use the selected building as a faithful cutout. Preserve facade rhythm, tower shape, massing, balcony/window pattern, and base structure. Do not add text/logo/signage onto the building facade. Put branding only as flat layout text. Do not add ocean, skyline, roads, or city unless visible in the selected asset."}'::jsonb),
  ('project_launch.bold_typographic.facade_mask.poster_stack.v1', 'Bold Typographic Facade Mask', 'A high-design poster where large typography frames or masks the truthful facade crop without inventing background context.', 'project_launch', ARRAY['4:5', '9:16']::text[], '{"style_family":"bold_typographic_luxury","hero_presentation":"facade_mask","layout_geometry":"poster_stack","graphic_layer":["large_type_mask","vertical_rules","caption_strip"],"type_voice":"fashion_editorial_sans","text_architecture":"big_type_project_name","mood_mode":"monochrome_warm_editorial","density":"medium","brand_visibility":"visible_brand_led","visual_mode":"editorialized_truth"}'::jsonb, '{"content_jobs":["project_launch"],"best_for":["fashion-magazine real estate poster","brand recall","launch announcement"],"avoid_when":["small format with heavy facts"],"reality_policy":"Use typography and masking for drama; do not create new scenery or claim new visible context."}'::jsonb),
  ('project_launch.luxury_blueprint.line_overlay.architectural_plate.v1', 'Luxury Blueprint Architecture Plate', 'A premium architectural plate with truthful facade/tower crop, fine blueprint lines, measurement-like rules, and restrained copy.', 'project_launch', ARRAY['4:5', '1:1']::text[], '{"style_family":"luxury_blueprint","hero_presentation":"tower_hero_launch","layout_geometry":"architectural_plate","graphic_layer":["blueprint_linework","measurement_rules","thin_frame","caption_grid"],"type_voice":"technical_editorial","text_architecture":"project_name_first","mood_mode":"deep_graphite_gallery","density":"medium","brand_visibility":"elegant_signature","visual_mode":"editorialized_truth"}'::jsonb, '{"content_jobs":["project_launch"],"best_for":["architecture-led launch","premium builder credibility","design-forward project identity"],"avoid_when":["festive or lifestyle-heavy creative"],"reality_policy":"Linework should be decorative/diagrammatic only, not fake floor plans, fake dimensions, or invented specs."}'::jsonb),
  ('project_launch.museum_label.hero_crop.exhibition_poster.v1', 'Museum Label Launch Poster', 'A gallery/exhibition-inspired launch poster with a precise project image crop, museum-label captioning, and quiet luxury spacing.', 'project_launch', ARRAY['4:5', '1:1']::text[], '{"style_family":"museum_editorial","hero_presentation":"tower_hero_launch","layout_geometry":"exhibition_poster","graphic_layer":["museum_label","wide_margin","thin_frame","caption_rule"],"type_voice":"quiet_premium","text_architecture":"one_statement","mood_mode":"gallery_white","density":"lean","brand_visibility":"whisper","visual_mode":"editorialized_truth"}'::jsonb, '{"content_jobs":["project_launch"],"best_for":["quiet luxury brand post","brochure-like launch creative","minimal high-end poster"],"avoid_when":["needs energetic campaign design"],"reality_policy":"Use the asset like a curated exhibit image; do not enhance it with ungrounded location elements."}'::jsonb),
  ('project_launch.cinematic_crop.noir_premium.title_card.v1', 'Cinematic Noir Title Card', 'A cinematic premium title-card layout using the real render/photo crop, deep tonal contrast, and restrained film-poster typography.', 'project_launch', ARRAY['4:5', '9:16']::text[], '{"style_family":"cinematic_noir_premium","hero_presentation":"facade_crop","layout_geometry":"title_card","graphic_layer":["letterbox_bands","subtle_vignette","fine_rule","low_contrast_texture"],"type_voice":"cinematic_serif","text_architecture":"slogan_first","mood_mode":"urban_night_premium","density":"lean","brand_visibility":"elegant_signature","visual_mode":"editorialized_truth"}'::jsonb, '{"content_jobs":["project_launch"],"best_for":["night/evening launch","premium teaser","film-poster style project identity"],"avoid_when":["brief asks for bright daylight"],"reality_policy":"Use grade, crop, and typography for cinema; do not add a new skyline, ocean, or city scene."}'::jsonb),
  ('pricing_ad.swiss_grid.subtle_architecture.bold_offer_centerpiece.v1', 'Swiss Offer Centerpiece', 'A premium proposition box ad where offer/price dominates and architecture supports subtly.', 'pricing_ad', ARRAY['4:5', '9:16']::text[], '{"style_family":"swiss_grid_premium","hero_presentation":"subtle_architecture_presence","layout_geometry":"bold_offer_centerpiece","graphic_layer":["proposition_box","divider_lines","micro_badges"],"type_voice":"bold_ad_hook","text_architecture":"hook_first","mood_mode":"ivory_studio_neutral","density":"medium","brand_visibility":"visible_brand_led","visual_mode":"editorialized_truth"}'::jsonb, '{"content_jobs":["pricing_ad"],"best_for":["pricing ad","EMI offer","conversion creative"],"avoid_when":["no grounded price/offer exists"]}'::jsonb),
  ('pricing_ad.graphic_led.cutout_offer.blob_stack.v1', 'Premium Cutout Offer Blob Stack', 'A premium offer-led template using a truthful building cutout with refined blob shapes and a strong proposition box.', 'pricing_ad', ARRAY['4:5']::text[], '{"style_family":"graphic_led","hero_presentation":"cutout_hero","layout_geometry":"blob_cutout","graphic_layer":["blob_shapes","proposition_box","micro_badges"],"type_voice":"bold_ad_hook","text_architecture":"hook_first","mood_mode":"ivory_studio_neutral","density":"medium","brand_visibility":"campaign_dominant","visual_mode":"editorialized_truth"}'::jsonb, '{"content_jobs":["pricing_ad"],"best_for":["pricing ads that need to look more social-first","offer posts where the building supports the commercial hook","ads that should avoid cheap flyer aesthetics"],"avoid_when":["no grounded pricing or offer exists","formal catalog-style ad is required","asset cannot be cropped or used as cutout"],"visual_notes":["Use the building as a truthful cutout, not as a fake new render.","Keep the offer as the visual hero.","Use blobs as premium graphic containers, not childish stickers.","Preserve all architectural truth."]}'::jsonb),
  ('pricing_ad.minimal.proposition_box.card_stack.v1', 'Minimal Price Card Stack', 'A clean stacked-card pricing template for two or three grounded claims.', 'pricing_ad', ARRAY['4:5']::text[], '{"style_family":"minimal","hero_presentation":"proposition_box","layout_geometry":"card_stack","graphic_layer":["proposition_box","divider_lines"],"type_voice":"modern_sans","text_architecture":"proof_second","mood_mode":"ivory_studio_neutral","density":"medium","brand_visibility":"visible_brand_led","visual_mode":"graphic_led"}'::jsonb, '{"content_jobs":["pricing_ad"],"best_for":["price list","unit comparison","clean conversion post"],"avoid_when":["architecture must be the hero"]}'::jsonb),
  ('pricing_ad.editorial_catalog.facade_crop.split_grid.v1', 'Editorial Price Split', 'A premium split-grid ad balancing facade crop with a sharp offer column.', 'pricing_ad', ARRAY['4:5']::text[], '{"style_family":"editorial_catalog","hero_presentation":"facade_crop","layout_geometry":"split_grid","graphic_layer":["thin_frame","divider_lines"],"type_voice":"premium_serif","text_architecture":"hook_first","mood_mode":"pale_editorial_daylight","density":"medium","brand_visibility":"visible_brand_led","visual_mode":"editorialized_truth"}'::jsonb, '{"content_jobs":["pricing_ad"],"best_for":["premium pricing ad","architecture + offer balance"],"avoid_when":["no building asset"]}'::jsonb),
  ('pricing_ad.graphic_led.proposition_box.split_grid.v1', 'Graphic Offer Split', 'A graphic-led offer post for cases where the offer is the full visual hero.', 'pricing_ad', ARRAY['4:5', '9:16']::text[], '{"style_family":"graphic_led","hero_presentation":"proposition_box","layout_geometry":"split_grid","graphic_layer":["geometric_blocks","proposition_box","micro_badges"],"type_voice":"bold_ad_hook","text_architecture":"proposition_first","mood_mode":"ivory_studio_neutral","density":"medium","brand_visibility":"campaign_dominant","visual_mode":"graphic_led"}'::jsonb, '{"content_jobs":["pricing_ad"],"best_for":["no building image","offer-led graphic","performance ad"],"avoid_when":["quiet editorial launch"]}'::jsonb),
  ('pricing_ad.brutalist.proposition_box.bold_offer_centerpiece.v1', 'Brutalist Premium Offer', 'A high-contrast bold offer template for sharper campaign variation.', 'pricing_ad', ARRAY['4:5']::text[], '{"style_family":"brutalist","hero_presentation":"proposition_box","layout_geometry":"bold_offer_centerpiece","graphic_layer":["geometric_blocks","divider_lines"],"type_voice":"bold_ad_hook","text_architecture":"hook_first","mood_mode":"urban_night_premium","density":"medium","brand_visibility":"campaign_dominant","visual_mode":"graphic_led"}'::jsonb, '{"content_jobs":["pricing_ad"],"best_for":["distinct ad variation","bold offer campaign"],"avoid_when":["soft luxury tone required"]}'::jsonb),
  ('amenity.editorial_catalog.symbolic_centerpiece.magazine_spread.v1', 'Symbolic Amenity Editorial', 'A refined symbolic amenity treatment when amenity image is missing or concept-led output is preferred.', 'amenity_spotlight', ARRAY['4:5']::text[], '{"style_family":"editorial_catalog","hero_presentation":"symbolic_centerpiece","layout_geometry":"magazine_spread","graphic_layer":["soft_gradient_field","paper_depth","thin_frame"],"type_voice":"quiet_premium","text_architecture":"one_statement","mood_mode":"pale_editorial_daylight","density":"lean","brand_visibility":"elegant_signature","visual_mode":"graphic_led"}'::jsonb, '{"content_jobs":["amenity_spotlight"],"best_for":["amenity without image","premium wellness/lifestyle concept"],"avoid_when":["user needs asset-faithful amenity proof"]}'::jsonb),
  ('amenity.quiet_luxury.amenity_scene.centered_symmetry.v1', 'Quiet Amenity Scene', 'A calm amenity-led composition for when a truthful amenity image exists.', 'amenity_spotlight', ARRAY['4:5', '1:1']::text[], '{"style_family":"quiet_luxury","hero_presentation":"amenity_scene","layout_geometry":"centered_symmetry","graphic_layer":["thin_frame","soft_gradient_field"],"type_voice":"quiet_premium","text_architecture":"one_statement","mood_mode":"crisp_daylight","density":"lean","brand_visibility":"elegant_signature","visual_mode":"asset_faithful"}'::jsonb, '{"content_jobs":["amenity_spotlight"],"best_for":["pool image","garden image","real amenity image"],"avoid_when":["no amenity asset exists"]}'::jsonb),
  ('amenity.graphic_led.symbolic_centerpiece.blob_cutout.v1', 'Graphic Amenity Blob', 'A playful but premium graphic amenity template using organic shapes and symbolic centerpieces.', 'amenity_spotlight', ARRAY['4:5']::text[], '{"style_family":"graphic_led","hero_presentation":"symbolic_centerpiece","layout_geometry":"blob_cutout","graphic_layer":["blob_shapes","line_art","soft_gradient_field"],"type_voice":"modern_sans","text_architecture":"one_statement","mood_mode":"ivory_studio_neutral","density":"medium","brand_visibility":"visible_brand_led","visual_mode":"graphic_led"}'::jsonb, '{"content_jobs":["amenity_spotlight"],"best_for":["amenity concept variations","festival/lifestyle overlays"],"avoid_when":["strict asset-faithful proof"]}'::jsonb),
  ('amenity.minimal.symbolic_centerpiece.card_stack.v1', 'Minimal Amenity Card', 'A minimal card-style amenity post centered on a single amenity name and symbol.', 'amenity_spotlight', ARRAY['4:5', '1:1']::text[], '{"style_family":"minimal","hero_presentation":"symbolic_centerpiece","layout_geometry":"card_stack","graphic_layer":["paper_depth","thin_frame"],"type_voice":"quiet_premium","text_architecture":"one_statement","mood_mode":"ivory_studio_neutral","density":"lean","brand_visibility":"whisper","visual_mode":"graphic_led"}'::jsonb, '{"content_jobs":["amenity_spotlight"],"best_for":["simple amenity post","low copy","clean design"],"avoid_when":["needs rich lifestyle photography"]}'::jsonb),
  ('location.graphic_led.symbolic_centerpiece.infographic_map.v1', 'Location Orbit Infographic', 'A schematic orbit/location graphic using verified nearby places, not an exact map.', 'location_advantage', ARRAY['4:5']::text[], '{"style_family":"graphic_led","hero_presentation":"symbolic_centerpiece","layout_geometry":"infographic_map","graphic_layer":["line_art","micro_badges","thin_frame"],"type_voice":"swiss_clean","text_architecture":"proposition_first","mood_mode":"ivory_studio_neutral","density":"medium","brand_visibility":"visible_brand_led","visual_mode":"graphic_led"}'::jsonb, '{"content_jobs":["location_advantage"],"best_for":["location advantage","schematic connectivity","verified places"],"avoid_when":["exact map accuracy required"]}'::jsonb),
  ('location.swiss_grid.symbolic_centerpiece.swiss_grid.v1', 'Swiss Location Facts', 'A clean typographic location advantage layout without a map.', 'location_advantage', ARRAY['4:5', '1:1']::text[], '{"style_family":"swiss_grid_premium","hero_presentation":"symbolic_centerpiece","layout_geometry":"swiss_grid","graphic_layer":["divider_lines","micro_badges"],"type_voice":"swiss_clean","text_architecture":"proof_second","mood_mode":"ivory_studio_neutral","density":"medium","brand_visibility":"visible_brand_led","visual_mode":"graphic_led"}'::jsonb, '{"content_jobs":["location_advantage"],"best_for":["location post without map","verified place list"],"avoid_when":["visual map requested"]}'::jsonb),
  ('location.minimal.symbolic_centerpiece.centered_symmetry.v1', 'Minimal Location Signal', 'A minimal location creative centered on one or two grounded location facts.', 'location_advantage', ARRAY['4:5']::text[], '{"style_family":"minimal","hero_presentation":"symbolic_centerpiece","layout_geometry":"centered_symmetry","graphic_layer":["thin_frame","line_art"],"type_voice":"modern_sans","text_architecture":"one_statement","mood_mode":"pale_editorial_daylight","density":"lean","brand_visibility":"elegant_signature","visual_mode":"graphic_led"}'::jsonb, '{"content_jobs":["location_advantage"],"best_for":["single location advantage","minimal creative"],"avoid_when":["many places must be shown"]}'::jsonb),
  ('site_visit.swiss_grid.facade_crop.swiss_grid.v1', 'Swiss Visit Planner', 'A structured visit-planner poster with clear CTA and optional contact/location.', 'site_visit', ARRAY['4:5']::text[], '{"style_family":"swiss_grid_premium","hero_presentation":"facade_crop","layout_geometry":"swiss_grid","graphic_layer":["thin_frame","divider_lines","geometric_blocks"],"type_voice":"swiss_clean","text_architecture":"proposition_first","mood_mode":"ivory_studio_neutral","density":"medium","brand_visibility":"visible_brand_led","visual_mode":"editorialized_truth"}'::jsonb, '{"content_jobs":["site_visit"],"best_for":["site visit","visit planner","lead action"],"avoid_when":["no project asset and no contact"]}'::jsonb),
  ('site_visit.editorial_catalog.facade_crop.magazine_spread.v1', 'Editorial Site Visit', 'A softer editorial site visit creative with architecture and refined visit CTA.', 'site_visit', ARRAY['4:5']::text[], '{"style_family":"editorial_catalog","hero_presentation":"facade_crop","layout_geometry":"magazine_spread","graphic_layer":["thin_frame","paper_depth"],"type_voice":"premium_serif","text_architecture":"cta_last","mood_mode":"pale_editorial_daylight","density":"lean","brand_visibility":"elegant_signature","visual_mode":"editorialized_truth"}'::jsonb, '{"content_jobs":["site_visit"],"best_for":["premium visit ad","soft lead generation"],"avoid_when":["many facts and contact details required"]}'::jsonb),
  ('site_visit.graphic_led.proposition_box.card_stack.v1', 'Graphic Visit CTA Card', 'A graphic-led visit CTA card for situations where the action should dominate.', 'site_visit', ARRAY['4:5', '9:16']::text[], '{"style_family":"graphic_led","hero_presentation":"proposition_box","layout_geometry":"card_stack","graphic_layer":["proposition_box","micro_badges","divider_lines"],"type_voice":"bold_ad_hook","text_architecture":"cta_last","mood_mode":"ivory_studio_neutral","density":"medium","brand_visibility":"campaign_dominant","visual_mode":"graphic_led"}'::jsonb, '{"content_jobs":["site_visit"],"best_for":["mobile story","lead CTA","no strong building image"],"avoid_when":["quiet luxury brand recall"]}'::jsonb)
)
insert into public.creative_v3_visual_templates (
  workspace_id,
  brand_id,
  project_id,
  post_type_id,
  template_key,
  name,
  description,
  content_job_id,
  allowed_formats,
  lever_signature,
  template_json,
  status
)
select
  w.id,
  null,
  null,
  null,
  s.template_key,
  s.name,
  s.description,
  s.content_job_id,
  s.allowed_formats,
  s.lever_signature,
  s.template_json,
  'approved'
from public.workspaces w
cross join template_seed s
on conflict (workspace_id, template_key) do update
set
  name = excluded.name,
  description = excluded.description,
  content_job_id = excluded.content_job_id,
  allowed_formats = excluded.allowed_formats,
  lever_signature = excluded.lever_signature,
  template_json = excluded.template_json,
  status = 'approved',
  updated_at = timezone('utc', now());
